version: "3.7"

services:

  # https://github.com/ivanfioravanti/chatbot-ollama
  chatbot:
    container_name: chatbot
    image: ghcr.io/ivanfioravanti/chatbot-ollama:main
    ports:
      - "127.0.0.1:3000:3000"
    environment:
      - DEFAULT_MODEL=llama2
      - OLLAMA_HOST=http://ollama:11434
    depends_on:
      - ollama

  # https://github.com/ollama-webui/ollama-webui
  webui:
    container_name: webui
    image: ghcr.io/ollama-webui/ollama-webui:main
    volumes:
      - "./ollama/ollama-webui:/app/backend/data"
    ports:
      - "127.0.0.1:3300:8080"
    environment:
        - OLLAMA_API_BASE_URL=http://ollama:11434/api
    depends_on:
      - ollama

  # https://hub.docker.com/r/ollama/ollama/tags
  ollama:
    container_name: ollama
    image: ollama/ollama:0.1.24
    volumes:
      - "./ollama/models:/ollama/models"
    environment:
      - OLLAMA_MODELS=/ollama/models
